version: 2

before:
  hooks:
    - go mod tidy
    - go run ./cmd/generate/

builds:
  - id: worksome
    main: ./cmd/worksome
    binary: worksome
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "worksome_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: worksome
      name: homebrew-tap
    name: worksome
    homepage: https://github.com/worksome/worksome-cli
    description: CLI for the Worksome API
    install: |
      bin.install "worksome"
