package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator produces Go source files from a parsed Schema IR.
type Generator struct {
	schema     *Schema
	outputDir  string
	modulePath string
}

// NewGenerator creates a new code generator.
func NewGenerator(schema *Schema, outputDir, modulePath string) *Generator {
	return &Generator{
		schema:     schema,
		outputDir:  outputDir,
		modulePath: modulePath,
	}
}

// Generate produces all Go source files.
func (g *Generator) Generate() error {
	if err := os.MkdirAll(filepath.Join(g.outputDir, "types"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(g.outputDir, "queries"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(g.outputDir, "commands"), 0o755); err != nil {
		return err
	}

	generators := []struct {
		name string
		fn   func() error
	}{
		{"enums", g.generateEnums},
		{"types", g.generateTypes},
		{"inputs", g.generateInputs},
		{"queries", g.generateQueries},
		{"commands", g.generateCommands},
		{"root", g.generateRoot},
	}

	for _, gen := range generators {
		fmt.Fprintf(os.Stderr, "  generating %s...\n", gen.name)
		if err := gen.fn(); err != nil {
			return fmt.Errorf("generating %s: %w", gen.name, err)
		}
	}

	return nil
}

func (g *Generator) generateEnums() error {
	tmpl := template.Must(template.New("enums").Parse(enumsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "enums.go"), map[string]any{
		"Enums": g.schema.Enums,
	})
}

func (g *Generator) generateTypes() error {
	tmpl := template.Must(template.New("types").Funcs(templateFuncs).Parse(typesTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "types.go"), map[string]any{
		"Objects":    g.schema.Objects,
		"Interfaces": g.schema.Interfaces,
		"Unions":     g.schema.Unions,
	})
}

func (g *Generator) generateInputs() error {
	tmpl := template.Must(template.New("inputs").Funcs(templateFuncs).Parse(inputsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "inputs.go"), map[string]any{
		"Inputs": g.schema.Inputs,
	})
}

func (g *Generator) generateQueries() error {
	tmpl := template.Must(template.New("queries").Funcs(templateFuncs).Parse(queriesTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "queries", "queries.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) generateCommands() error {
	tmpl := template.Must(template.New("commands").Funcs(templateFuncs).Parse(commandsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "commands", "commands.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) generateRoot() error {
	tmpl := template.Must(template.New("root").Funcs(templateFuncs).Parse(rootTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "commands", "root.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) writeTemplate(tmpl *template.Template, path string, data any) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template for %s: %w", path, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		os.WriteFile(path+".unformatted", buf.Bytes(), 0o644)
		return fmt.Errorf("formatting %s: %w (unformatted written to %s.unformatted)", path, err, path)
	}

	return os.WriteFile(path, formatted, 0o644)
}

var templateFuncs = template.FuncMap{
	"lower":     strings.ToLower,
	"kebab":     toKebabCase,
	"pascal":    toPascalCase,
	"hasPrefix": strings.HasPrefix,
	"hasSuffix": strings.HasSuffix,
	"trimPrefix": strings.TrimPrefix,
	"join":      strings.Join,
	"jsonTag": func(name string, omitempty bool) string {
		if omitempty {
			return fmt.Sprintf("`json:\"%s,omitempty\"`", name)
		}
		return fmt.Sprintf("`json:\"%s\"`", name)
	},
	"isPtr": func(goType string) bool {
		return strings.HasPrefix(goType, "*")
	},
	"deref": func(goType string) string {
		return strings.TrimPrefix(goType, "*")
	},
	"quote": func(s string) string {
		return fmt.Sprintf("%q", s)
	},
	"commentBlock": func(s string) string {
		if s == "" {
			return ""
		}
		lines := strings.Split(s, "\n")
		var result []string
		for _, line := range lines {
			result = append(result, "// "+line)
		}
		return strings.Join(result, "\n")
	},
}

// Templates

var enumsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range $enum := .Enums}}
{{if $enum.Description}}// {{$enum.GoName}} — {{$enum.Description}}{{end}}
type {{$enum.GoName}} string

const (
{{- range $enum.Values}}
	{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
	{{.GoName}} {{$enum.GoName}} = "{{.Name}}"
{{- end}}
)

// Valid{{$enum.GoName}} returns all valid values for {{$enum.GoName}}.
func Valid{{$enum.GoName}}() []{{$enum.GoName}} {
	return []{{$enum.GoName}}{
	{{- range $enum.Values}}
		{{.GoName}},
	{{- end}}
	}
}
{{end}}
`

var typesTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range .Interfaces}}
{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
type {{.GoName}} interface {
	Is{{.GoName}}()
}
{{end}}

{{range .Unions}}
// {{.GoName}} is a GraphQL union type.
type {{.GoName}} interface {
	Is{{.GoName}}()
}
{{end}}

{{range $obj := .Objects}}
{{if $obj.Description}}// {{$obj.GoName}} — {{$obj.Description}}{{end}}
type {{$obj.GoName}} struct {
{{- range $obj.Fields}}
	{{if .Description}}// {{.Description}}{{end}}
	{{.GoName}} {{.Type.GoType}} {{jsonTag .JSONName (not .Type.IsRequired)}}
{{- end}}
}
{{range $obj.Implements}}
func ({{$obj.GoName}}) Is{{.}}() {}
{{- end}}
{{end}}
`

var inputsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range .Inputs}}
{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
type {{.GoName}} struct {
{{- range .Fields}}
	{{if .Description}}// {{.Description}}{{end}}
	{{.GoName}} {{.Type.GoType}} {{jsonTag .Name (not .Type.IsRequired)}}
{{- end}}
}
{{end}}
`

var queriesTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package queries

import (
	"context"
	"fmt"

	"{{.ModulePath}}/internal/client"
)

// Querier wraps the GraphQL client for executing generated operations.
type Querier struct {
	Client *client.Client
}

// NewQuerier creates a new Querier.
func NewQuerier(c *client.Client) *Querier {
	return &Querier{Client: c}
}

{{range .Resources}}
{{- if .GetQuery}}
// {{.GetQuery.GoName}} — {{.GetQuery.Description}}
func (q *Querier) {{.GetQuery.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `query {{.GetQuery.GoName}}{{buildQueryArgs .GetQuery.Arguments}} {
	{{.GetQuery.Name}}{{buildQueryCallArgs .GetQuery.Arguments}} {{.GetQuery.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.GetQuery.Name}}: %w", err)
	}
	if data, ok := result["{{.GetQuery.Name}}"]; ok {
		if m, ok := data.(map[string]any); ok {
			return m, nil
		}
	}
	return result, nil
}
{{end}}

{{- if .ListQuery}}
// {{.ListQuery.GoName}} — {{.ListQuery.Description}}
func (q *Querier) {{.ListQuery.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `query {{.ListQuery.GoName}}{{buildQueryArgs .ListQuery.Arguments}} {
	{{.ListQuery.Name}}{{buildQueryCallArgs .ListQuery.Arguments}} {{.ListQuery.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.ListQuery.Name}}: %w", err)
	}
	return result, nil
}
{{end}}

{{- range .Mutations}}
// {{.GoName}} — {{.Description}}
func (q *Querier) {{.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `mutation {{.GoName}}{{buildMutationArgs .Arguments}} {
	{{.Name}}{{buildMutationCallArgs .Arguments}} {{.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}: %w", err)
	}
	if data, ok := result["{{.Name}}"]; ok {
		if m, ok := data.(map[string]any); ok {
			return m, nil
		}
	}
	return result, nil
}
{{end}}
{{end}}
`

var commandsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"{{.ModulePath}}/internal/client"
	"{{.ModulePath}}/internal/generated/queries"
	"{{.ModulePath}}/internal/output"
)

// clientFactory is set by the root command to create authenticated clients.
var clientFactory func() (*client.Client, error)

// SetClientFactory sets the function used to create GraphQL clients.
func SetClientFactory(f func() (*client.Client, error)) {
	clientFactory = f
}

func getQuerier() (*queries.Querier, error) {
	if clientFactory == nil {
		return nil, fmt.Errorf("client not configured — call SetClientFactory first")
	}
	c, err := clientFactory()
	if err != nil {
		return nil, err
	}
	return queries.NewQuerier(c), nil
}

func getFormatter(cmd *cobra.Command) *output.Formatter {
	outputFlag, _ := cmd.Flags().GetString("output")
	noColor, _ := cmd.Flags().GetBool("no-color")
	if outputFlag != "" {
		return output.New(os.Stdout, output.Format(outputFlag), noColor)
	}
	return output.Auto(os.Stdout, noColor)
}

func printResult(cmd *cobra.Command, data any) error {
	f := getFormatter(cmd)
	return f.PrintJSON(data)
}

func readInputFile(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading input file: %w", err)
	}
	var result map[string]any
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, fmt.Errorf("parsing input file: %w", err)
	}
	return result, nil
}

{{range $res := .Resources}}
// New{{$res.GoName}}Cmd creates the {{$res.Name}} resource command group.
func New{{$res.GoName}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{$res.Name}}",
		Short: {{quote $res.Description}},
	}

	{{if $res.GetQuery -}}
	cmd.AddCommand(new{{$res.GoName}}GetCmd())
	{{end -}}
	{{if $res.ListQuery -}}
	cmd.AddCommand(new{{$res.GoName}}ListCmd())
	{{end -}}
	{{range $res.Mutations -}}
	cmd.AddCommand(new{{$res.GoName}}{{pascal .CLIName}}Cmd())
	{{end}}
	return cmd
}

{{if $res.GetQuery}}
func new{{$res.GoName}}GetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: {{quote $res.GetQuery.Description}},
		{{- if hasIDArg $res.GetQuery.Arguments}}
		Args: cobra.ExactArgs(1),
		{{- end}}
		RunE: func(cmd *cobra.Command, args []string) error {
			q, err := getQuerier()
			if err != nil {
				return err
			}
			vars := make(map[string]any)
			{{- if hasIDArg $res.GetQuery.Arguments}}
			vars["id"] = args[0]
			{{- end}}
			{{- range $res.GetQuery.Arguments}}
			{{- if ne .Name "id"}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				vars["{{.Name}}"] = v
			}
			{{- end}}
			{{- end}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "query", vars)
			}

			result, err := q.{{$res.GetQuery.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			return printResult(cmd, result)
		},
	}
	{{range $res.GetQuery.Arguments -}}
	{{if ne .Name "id" -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote .Description}})
	{{end -}}
	{{end}}
	return cmd
}
{{end}}

{{if $res.ListQuery}}
func new{{$res.GoName}}ListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: {{quote $res.ListQuery.Description}},
		RunE: func(cmd *cobra.Command, args []string) error {
			q, err := getQuerier()
			if err != nil {
				return err
			}
			vars := make(map[string]any)
			first, _ := cmd.Flags().GetInt("first")
			vars["first"] = first
			if cmd.Flags().Changed("page") {
				page, _ := cmd.Flags().GetInt("page")
				vars["page"] = page
			}
			{{- range $res.ListQuery.Arguments}}
			{{- if and (ne .Name "first") (ne .Name "page")}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				vars["{{.Name}}"] = v
			}
			{{- end}}
			{{- end}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "query", vars)
			}

			fetchAll, _ := cmd.Flags().GetBool("all")
			if fetchAll {
				return {{$res.GoName | lower}}FetchAll(cmd, q, vars)
			}

			result, err := q.{{$res.ListQuery.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			return printResult(cmd, result)
		},
	}
	cmd.Flags().Int("first", 10, "Number of items to fetch per page")
	cmd.Flags().Int("page", 1, "Page number")
	cmd.Flags().Bool("all", false, "Fetch all pages")
	{{range $res.ListQuery.Arguments -}}
	{{if and (ne .Name "first") (ne .Name "page") -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote .Description}})
	{{end -}}
	{{end}}
	return cmd
}

func {{$res.GoName | lower}}FetchAll(cmd *cobra.Command, q *queries.Querier, vars map[string]any) error {
	var allData []any
	page := 1
	for {
		vars["page"] = page
		result, err := q.{{$res.ListQuery.GoName}}(context.Background(), vars)
		if err != nil {
			return fmt.Errorf("page %d: %w", page, err)
		}
		// Extract data array from paginator response
		if paginator, ok := result["{{$res.ListQuery.Name}}"].(map[string]any); ok {
			if data, ok := paginator["data"].([]any); ok {
				allData = append(allData, data...)
			}
			if info, ok := paginator["paginatorInfo"].(map[string]any); ok {
				if hasMore, ok := info["hasMorePages"].(bool); ok && !hasMore {
					break
				}
			} else {
				break
			}
		} else {
			// Not a paginator response, return single result
			return printResult(cmd, result)
		}
		page++
	}
	return printResult(cmd, allData)
}
{{end}}

{{range $mut := $res.Mutations}}
func new{{$res.GoName}}{{pascal $mut.CLIName}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{$mut.CLIName}}",
		Short: {{quote $mut.Description}},
		RunE: func(cmd *cobra.Command, args []string) error {
			q, err := getQuerier()
			if err != nil {
				return err
			}
			vars := make(map[string]any)

			// Load from input file if provided
			inputFile, _ := cmd.Flags().GetString("input")
			if inputFile != "" {
				fileVars, err := readInputFile(inputFile)
				if err != nil {
					return err
				}
				vars["input"] = fileVars
			}

			{{if $mut.InputFields -}}
			// Build input object from flags (flags override file values)
			inputObj, _ := vars["input"].(map[string]any)
			if inputObj == nil {
				inputObj = make(map[string]any)
			}
			{{range $mut.InputFields -}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				{{- if eq .Type.GoType "int" "float64"}}
				v, _ := cmd.Flags().Get{{if eq .Type.GoType "int"}}Int{{else}}Float64{{end}}("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq .Type.GoType "bool"}}
				v, _ := cmd.Flags().GetBool("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else}}
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- end}}
			}
			{{end -}}
			vars["input"] = inputObj
			{{end -}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "mutation", vars)
			}

			result, err := q.{{$mut.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			return printResult(cmd, result)
		},
	}
	cmd.Flags().String("input", "", "Path to JSON input file")
	{{range $mut.InputFields -}}
	{{if eq .Type.GoType "int" -}}
	cmd.Flags().Int("{{.CLIFlag}}", 0, {{quote .Description}})
	{{else if eq .Type.GoType "float64" -}}
	cmd.Flags().Float64("{{.CLIFlag}}", 0, {{quote .Description}})
	{{else if eq .Type.GoType "bool" -}}
	cmd.Flags().Bool("{{.CLIFlag}}", false, {{quote .Description}})
	{{else -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote .Description}})
	{{end -}}
	{{end -}}
	return cmd
}
{{end}}
{{end}}

func printDryRun(cmd *cobra.Command, opType string, vars map[string]any) error {
	fmt.Fprintf(os.Stderr, "[dry-run] Operation type: %s\n", opType)
	data, _ := json.MarshalIndent(vars, "", "  ")
	fmt.Fprintf(os.Stdout, "%s\n", data)
	return nil
}
`

var rootTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package commands

import "github.com/spf13/cobra"

// RegisterAll adds all generated resource commands to the root command.
func RegisterAll(root *cobra.Command) {
{{- range $res := .Resources}}
	root.AddCommand(New{{$res.GoName}}Cmd())
{{- end}}
}
`

func init() {
	// Register additional template functions for query building
	templateFuncs["buildQueryArgs"] = buildQueryArgs
	templateFuncs["buildQueryCallArgs"] = buildQueryCallArgs
	templateFuncs["buildMutationArgs"] = buildMutationArgs
	templateFuncs["buildMutationCallArgs"] = buildMutationCallArgs
	templateFuncs["buildSelectionHint"] = buildSelectionHint
	templateFuncs["hasIDArg"] = hasIDArg
	templateFuncs["not"] = func(b bool) bool { return !b }
}

func buildQueryArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		gqlType := a.Type.Name
		if a.Type.IsList {
			gqlType = "[" + a.Type.ListItem.Name + "]"
			if a.Type.ListItem.IsRequired {
				gqlType = "[" + a.Type.ListItem.Name + "!]"
			}
		}
		if a.Type.IsRequired {
			gqlType += "!"
		}
		def := ""
		if a.DefaultValue != "" {
			def = " = " + a.DefaultValue
		}
		parts = append(parts, fmt.Sprintf("$%s: %s%s", a.Name, gqlType, def))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildQueryCallArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		parts = append(parts, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildMutationArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		gqlType := a.Type.Name
		if a.Type.IsList {
			inner := a.Type.ListItem.Name
			if a.Type.ListItem.IsRequired {
				inner += "!"
			}
			gqlType = "[" + inner + "]"
		}
		if a.Type.IsRequired {
			gqlType += "!"
		}
		parts = append(parts, fmt.Sprintf("$%s: %s", a.Name, gqlType))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildMutationCallArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		parts = append(parts, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildSelectionHint(t TypeRef) string {
	if t.IsPaginator {
		return "{ id }"
	}
	if t.IsList {
		return "{ id }"
	}
	if t.IsScalar || t.IsEnum {
		return ""
	}
	return "{ id }"
}

func hasIDArg(args []Argument) bool {
	for _, a := range args {
		if a.Name == "id" {
			return true
		}
	}
	return false
}
