package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator produces Go source files from a parsed Schema IR.
type Generator struct {
	schema     *Schema
	outputDir  string
	modulePath string
}

// NewGenerator creates a new code generator.
func NewGenerator(schema *Schema, outputDir, modulePath string) *Generator {
	return &Generator{
		schema:     schema,
		outputDir:  outputDir,
		modulePath: modulePath,
	}
}

// Generate produces all Go source files.
func (g *Generator) Generate() error {
	if err := os.MkdirAll(filepath.Join(g.outputDir, "types"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(g.outputDir, "queries"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(g.outputDir, "commands"), 0o755); err != nil {
		return err
	}

	generators := []struct {
		name string
		fn   func() error
	}{
		{"enums", g.generateEnums},
		{"types", g.generateTypes},
		{"inputs", g.generateInputs},
		{"queries", g.generateQueries},
		{"commands", g.generateCommands},
		{"root", g.generateRoot},
	}

	for _, gen := range generators {
		fmt.Fprintf(os.Stderr, "  generating %s...\n", gen.name)
		if err := gen.fn(); err != nil {
			return fmt.Errorf("generating %s: %w", gen.name, err)
		}
	}

	return nil
}

func (g *Generator) generateEnums() error {
	tmpl := template.Must(template.New("enums").Parse(enumsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "enums.go"), map[string]any{
		"Enums": g.schema.Enums,
	})
}

func (g *Generator) generateTypes() error {
	tmpl := template.Must(template.New("types").Funcs(templateFuncs).Parse(typesTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "types.go"), map[string]any{
		"Objects":    g.schema.Objects,
		"Interfaces": g.schema.Interfaces,
		"Unions":     g.schema.Unions,
	})
}

func (g *Generator) generateInputs() error {
	tmpl := template.Must(template.New("inputs").Funcs(templateFuncs).Parse(inputsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "types", "inputs.go"), map[string]any{
		"Inputs": g.schema.Inputs,
	})
}

func (g *Generator) generateQueries() error {
	tmpl := template.Must(template.New("queries").Funcs(templateFuncs).Parse(queriesTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "queries", "queries.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) generateCommands() error {
	tmpl := template.Must(template.New("commands").Funcs(templateFuncs).Parse(commandsTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "commands", "commands.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) generateRoot() error {
	tmpl := template.Must(template.New("root").Funcs(templateFuncs).Parse(rootTemplate))
	return g.writeTemplate(tmpl, filepath.Join(g.outputDir, "commands", "root.go"), map[string]any{
		"Resources":  g.schema.Resources,
		"ModulePath": g.modulePath,
	})
}

func (g *Generator) writeTemplate(tmpl *template.Template, path string, data any) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template for %s: %w", path, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		_ = os.WriteFile(path+".unformatted", buf.Bytes(), 0o644)
		return fmt.Errorf("formatting %s: %w (unformatted written to %s.unformatted)", path, err, path)
	}

	return os.WriteFile(path, formatted, 0o644)
}

var templateFuncs = template.FuncMap{
	"lower":     strings.ToLower,
	"kebab":     toKebabCase,
	"pascal":    toPascalCase,
	"hasPrefix": strings.HasPrefix,
	"hasSuffix": strings.HasSuffix,
	"trimPrefix": strings.TrimPrefix,
	"join":      strings.Join,
	"jsonTag": func(name string, omitempty bool) string {
		if omitempty {
			return fmt.Sprintf("`json:\"%s,omitempty\"`", name)
		}
		return fmt.Sprintf("`json:\"%s\"`", name)
	},
	"isPtr": func(goType string) bool {
		return strings.HasPrefix(goType, "*")
	},
	"deref": func(goType string) string {
		return strings.TrimPrefix(goType, "*")
	},
	"quote": func(s string) string {
		return fmt.Sprintf("%q", s)
	},
	"commentBlock": func(s string) string {
		if s == "" {
			return ""
		}
		lines := strings.Split(s, "\n")
		var result []string
		for _, line := range lines {
			result = append(result, "// "+line)
		}
		return strings.Join(result, "\n")
	},
}

// Templates

var enumsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range $enum := .Enums}}
{{if $enum.Description}}// {{$enum.GoName}} — {{$enum.Description}}{{end}}
type {{$enum.GoName}} string

const (
{{- range $enum.Values}}
	{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
	{{.GoName}} {{$enum.GoName}} = "{{.Name}}"
{{- end}}
)

// Valid{{$enum.GoName}} returns all valid values for {{$enum.GoName}}.
func Valid{{$enum.GoName}}() []{{$enum.GoName}} {
	return []{{$enum.GoName}}{
	{{- range $enum.Values}}
		{{.GoName}},
	{{- end}}
	}
}
{{end}}
`

var typesTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range .Interfaces}}
{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
type {{.GoName}} interface {
	Is{{.GoName}}()
}
{{end}}

{{range .Unions}}
// {{.GoName}} is a GraphQL union type.
type {{.GoName}} interface {
	Is{{.GoName}}()
}
{{end}}

{{range $obj := .Objects}}
{{if $obj.Description}}// {{$obj.GoName}} — {{$obj.Description}}{{end}}
type {{$obj.GoName}} struct {
{{- range $obj.Fields}}
	{{if .Description}}// {{.Description}}{{end}}
	{{.GoName}} {{.Type.GoType}} {{jsonTag .JSONName (not .Type.IsRequired)}}
{{- end}}
}
{{range $obj.Implements}}
func ({{$obj.GoName}}) Is{{.}}() {}
{{- end}}
{{end}}
`

var inputsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package types

{{range .Inputs}}
{{if .Description}}// {{.GoName}} — {{.Description}}{{end}}
type {{.GoName}} struct {
{{- range .Fields}}
	{{if .Description}}// {{.Description}}{{end}}
	{{.GoName}} {{.Type.GoType}} {{jsonTag .Name (not .Type.IsRequired)}}
{{- end}}
}
{{end}}
`

var queriesTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package queries

import (
	"context"
	"fmt"

	"{{.ModulePath}}/internal/client"
)

// Querier wraps the GraphQL client for executing generated operations.
type Querier struct {
	Client *client.Client
}

// NewQuerier creates a new Querier.
func NewQuerier(c *client.Client) *Querier {
	return &Querier{Client: c}
}

{{range .Resources}}
{{- if .GetQuery}}
// {{.GetQuery.GoName}} — {{.GetQuery.Description}}
func (q *Querier) {{.GetQuery.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `query {{.GetQuery.GoName}}{{buildQueryArgs .GetQuery.Arguments}} {
	{{.GetQuery.Name}}{{buildQueryCallArgs .GetQuery.Arguments}} {{.GetQuery.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.GetQuery.Name}}: %w", err)
	}
	if data, ok := result["{{.GetQuery.Name}}"]; ok {
		if m, ok := data.(map[string]any); ok {
			return m, nil
		}
	}
	return result, nil
}
{{end}}

{{- if .ListQuery}}
// {{.ListQuery.GoName}} — {{.ListQuery.Description}}
func (q *Querier) {{.ListQuery.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `query {{.ListQuery.GoName}}{{buildQueryArgs .ListQuery.Arguments}} {
	{{.ListQuery.Name}}{{buildQueryCallArgs .ListQuery.Arguments}} {{.ListQuery.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.ListQuery.Name}}: %w", err)
	}
	return result, nil
}
{{end}}

{{- range .Mutations}}
// {{.GoName}} — {{.Description}}
func (q *Querier) {{.GoName}}(ctx context.Context, vars map[string]any) (map[string]any, error) {
	query := ` + "`" + `mutation {{.GoName}}{{buildMutationArgs .Arguments}} {
	{{.Name}}{{buildMutationCallArgs .Arguments}} {{.SelectionSet}}
}` + "`" + `
	var result map[string]any
	err := q.Client.Execute(ctx, query, vars, &result)
	if err != nil {
		return nil, fmt.Errorf("{{.Name}}: %w", err)
	}
	if data, ok := result["{{.Name}}"]; ok {
		if m, ok := data.(map[string]any); ok {
			return m, nil
		}
	}
	return result, nil
}
{{end}}
{{end}}
`

var commandsTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package commands

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"{{.ModulePath}}/internal/client"
	"{{.ModulePath}}/internal/generated/queries"
	"{{.ModulePath}}/internal/output"
)

// clientFactory is set by the root command to create authenticated clients.
var clientFactory func() (*client.Client, error)

// SetClientFactory sets the function used to create GraphQL clients.
func SetClientFactory(f func() (*client.Client, error)) {
	clientFactory = f
}

func getQuerier() (*queries.Querier, error) {
	if clientFactory == nil {
		return nil, fmt.Errorf("client not configured — call SetClientFactory first")
	}
	c, err := clientFactory()
	if err != nil {
		return nil, err
	}
	return queries.NewQuerier(c), nil
}

func getFormatter(cmd *cobra.Command) (*output.Formatter, error) {
	outputFlag, _ := cmd.Flags().GetString("output")
	noColor, _ := cmd.Flags().GetBool("no-color")
	if outputFlag != "" {
		if outputFlag != "json" && outputFlag != "table" {
			return nil, fmt.Errorf("invalid output format %q: must be 'json' or 'table'", outputFlag)
		}
		return output.New(os.Stdout, output.Format(outputFlag), noColor), nil
	}
	return output.Auto(os.Stdout, noColor), nil
}

func printResult(cmd *cobra.Command, data any, columns []output.Column) error {
	if colFlag, _ := cmd.Flags().GetString("columns"); colFlag != "" {
		columns = output.FilterColumns(columns, colFlag)
	}
	fieldsFlag, _ := cmd.Root().PersistentFlags().GetString("fields")
	if fieldsFlag != "" {
		fields := strings.Split(fieldsFlag, ",")
		data = output.FilterFields(data, fields)
	}

	f, err := getFormatter(cmd)
	if err != nil {
		return err
	}
	if f.Format() == output.FormatTable && len(columns) > 0 {
		return f.PrintTable(data, columns)
	}
	if f.Format() == output.FormatTable && len(columns) == 0 {
		fmt.Fprintln(os.Stderr, "(table format not available for this resource, showing JSON)")
	}
	return f.PrintJSON(data)
}

func readInputFile(path string) (map[string]any, error) {
	var data []byte
	var err error
	if path == "-" {
		data, err = io.ReadAll(os.Stdin)
	} else {
		data, err = os.ReadFile(path)
	}
	if err != nil {
		return nil, fmt.Errorf("reading input: %w", err)
	}
	var result map[string]any
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, fmt.Errorf("parsing input: %w", err)
	}
	return result, nil
}

{{range $res := .Resources}}
{{- if $res.TableColumns}}
var {{$res.GoName | lower}}Columns = []output.Column{
{{- range $res.TableColumns}}
	{Header: {{quote .Header}}, Field: {{quote .Field}}},
{{- end}}
}
{{- end}}

{{- if $res.Hoisted}}
{{- $mut := index $res.Mutations 0}}
{{- if $mut.TableColumns}}
var {{$res.GoName | lower}}HoistedColumns = []output.Column{
{{- range $mut.TableColumns}}
	{Header: {{quote .Header}}, Field: {{quote .Field}}},
{{- end}}
}
{{- end}}
{{- end}}

// New{{$res.GoName}}Cmd creates the {{$res.Name}} resource command.
func New{{$res.GoName}}Cmd() *cobra.Command {
{{- if $res.Hoisted}}
	{{- $mut := index $res.Mutations 0}}
	cmd := &cobra.Command{
		Use:   "{{$res.Name}}",
		Short: {{quote (shortDesc $mut.Description)}},
		{{- if $mut.InputExample}}
		Example: {{inputExampleBlockHoisted $res.Name $mut.InputFields $mut.InputExample | quote}},
		{{- else if $mut.InputFields}}
		Example: "  worksome {{$res.Name}} --input data.json{{with inputFlagExampleHoisted $res.Name $mut.InputFields}}\n  {{.}}{{end}}",
		{{- end}}
		RunE: func(cmd *cobra.Command, args []string) error {
			// Validate output format
			if outputFlag, _ := cmd.Flags().GetString("output"); outputFlag != "" {
				if outputFlag != "json" && outputFlag != "table" {
					return fmt.Errorf("invalid output format %q: must be 'json' or 'table'", outputFlag)
				}
			}

			vars := make(map[string]any)

			// Load from input file if provided
			inputFile, _ := cmd.Flags().GetString("input")
			if inputFile != "" {
				fileVars, err := readInputFile(inputFile)
				if err != nil {
					return err
				}
				vars["input"] = fileVars
			}

			{{if $mut.InputFields -}}
			// Build input object from flags (flags override file values)
			inputObj, _ := vars["input"].(map[string]any)
			if inputObj == nil {
				inputObj = make(map[string]any)
			}
			{{range $mut.InputFields -}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				{{- if eq (flagBaseType .Type) "int"}}
				v, _ := cmd.Flags().GetInt("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "float64"}}
				v, _ := cmd.Flags().GetFloat64("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "bool"}}
				v, _ := cmd.Flags().GetBool("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "stringSlice"}}
				v, _ := cmd.Flags().GetStringSlice("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else}}
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- end}}
			}
			{{end -}}
			vars["input"] = inputObj

			if len(inputObj) == 0 && inputFile == "" {
				fmt.Fprintln(os.Stderr, "Warning: no input provided; use --input <file> or set individual flags")
			}
			{{end -}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "mutation", "{{$mut.GoName}}", vars)
			}

			q, err := getQuerier()
			if err != nil {
				return err
			}

			result, err := q.{{$mut.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			{{- if $mut.TableColumns}}
			return printResult(cmd, result, {{$res.GoName | lower}}HoistedColumns)
			{{- else}}
			return printResult(cmd, result, nil)
			{{- end}}
		},
	}
	cmd.Flags().String("input", "", "Path to JSON input file (use - for stdin)")
	{{range $mut.InputFields -}}
	{{if eq (flagBaseType .Type) "int" -}}
	cmd.Flags().Int("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "float64" -}}
	cmd.Flags().Float64("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "bool" -}}
	cmd.Flags().Bool("{{.CLIFlag}}", false, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "stringSlice" -}}
	cmd.Flags().StringSlice("{{.CLIFlag}}", nil, {{quote (enumHint .Description .Type)}})
	{{else -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote (enumHint .Description .Type)}})
	{{end -}}
	{{end -}}
	{{range $mut.InputFields -}}
	{{if .Type.IsEnum -}}
	cmd.RegisterFlagCompletionFunc("{{.CLIFlag}}", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return {{enumValuesLiteral .Type.EnumValues}}, cobra.ShellCompDirectiveNoFileComp
	})
	{{end -}}
	{{end -}}
	return cmd
{{- else}}
	cmd := &cobra.Command{
		Use:   "{{$res.Name}}",
		Short: {{quote (shortDesc $res.Description)}},
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}

	{{if $res.GetQuery -}}
	cmd.AddCommand(new{{$res.GoName}}GetCmd())
	{{end -}}
	{{if $res.ListQuery -}}
	cmd.AddCommand(new{{$res.GoName}}ListCmd())
	{{end -}}
	{{range $res.Mutations -}}
	cmd.AddCommand(new{{$res.GoName}}{{pascal .CLIName}}Cmd())
	{{end}}
	return cmd
{{- end}}
}

{{if not $res.Hoisted}}
{{if $res.GetQuery}}
func new{{$res.GoName}}GetCmd() *cobra.Command {
	cmd := &cobra.Command{
		{{- if hasIDArg $res.GetQuery.Arguments}}
		Use:   "get <id>",
		{{- else}}
		Use:   "get",
		{{- end}}
		Short: {{quote $res.GetQuery.Description}},
		Example: "  worksome {{$res.Name}} get <id>",
		{{- if hasIDArg $res.GetQuery.Arguments}}
		Args: cobra.ExactArgs(1),
		{{- end}}
		RunE: func(cmd *cobra.Command, args []string) error {
			// Validate output format
			if outputFlag, _ := cmd.Flags().GetString("output"); outputFlag != "" {
				if outputFlag != "json" && outputFlag != "table" {
					return fmt.Errorf("invalid output format %q: must be 'json' or 'table'", outputFlag)
				}
			}

			vars := make(map[string]any)
			{{- if hasIDArg $res.GetQuery.Arguments}}
			vars["id"] = args[0]
			{{- end}}
			{{- range $res.GetQuery.Arguments}}
			{{- if ne .Name "id"}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				{{- if eq (flagBaseType .Type) "bool"}}
				v, _ := cmd.Flags().GetBool("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "int"}}
				v, _ := cmd.Flags().GetInt("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "float64"}}
				v, _ := cmd.Flags().GetFloat64("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "stringSlice"}}
				v, _ := cmd.Flags().GetStringSlice("{{.CLIFlag}}")
				{{- else}}
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				{{- end}}
				vars["{{.Name}}"] = v
			}
			{{- end}}
			{{- end}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "query", "{{$res.GetQuery.GoName}}", vars)
			}

			q, err := getQuerier()
			if err != nil {
				return err
			}

			result, err := q.{{$res.GetQuery.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			{{- if $res.TableColumns}}
			return printResult(cmd, result, {{$res.GoName | lower}}Columns)
			{{- else}}
			return printResult(cmd, result, nil)
			{{- end}}
		},
	}
	{{range $res.GetQuery.Arguments -}}
	{{if ne .Name "id" -}}
	{{if eq (flagBaseType .Type) "bool" -}}
	cmd.Flags().Bool("{{.CLIFlag}}", false, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "int" -}}
	cmd.Flags().Int("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "float64" -}}
	cmd.Flags().Float64("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "stringSlice" -}}
	cmd.Flags().StringSlice("{{.CLIFlag}}", nil, {{quote (enumHint .Description .Type)}})
	{{else -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote (enumHint .Description .Type)}})
	{{end -}}
	{{end -}}
	{{end -}}
	{{range $res.GetQuery.Arguments -}}
	{{if and (ne .Name "id") .Type.IsRequired -}}
	_ = cmd.MarkFlagRequired("{{.CLIFlag}}")
	{{end -}}
	{{end}}
	{{range $res.GetQuery.Arguments -}}
	{{if and (ne .Name "id") .Type.IsEnum -}}
	cmd.RegisterFlagCompletionFunc("{{.CLIFlag}}", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return {{enumValuesLiteral .Type.EnumValues}}, cobra.ShellCompDirectiveNoFileComp
	})
	{{end -}}
	{{end}}
	return cmd
}
{{end}}

{{if $res.ListQuery}}
func new{{$res.GoName}}ListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: {{quote $res.ListQuery.Description}},
		Example: "  worksome {{$res.Name}} list -n 20\n  worksome {{$res.Name}} list --all\n  worksome {{$res.Name}} list --watch\n  worksome {{$res.Name}} list --watch --watch-interval 10",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Apply --filter shorthand before reading individual flags
			if err := output.ApplyFilterFlag(cmd); err != nil {
				return err
			}

			// Validate output format
			if outputFlag, _ := cmd.Flags().GetString("output"); outputFlag != "" {
				if outputFlag != "json" && outputFlag != "table" {
					return fmt.Errorf("invalid output format %q: must be 'json' or 'table'", outputFlag)
				}
			}

			vars := make(map[string]any)
			first, _ := cmd.Flags().GetInt("first")
			if first <= 0 {
				return fmt.Errorf("--first must be a positive integer")
			}
			vars["first"] = first
			if cmd.Flags().Changed("page") {
				page, _ := cmd.Flags().GetInt("page")
				vars["page"] = page
			}
			{{- range $res.ListQuery.Arguments}}
			{{- if and (ne .Name "first") (ne .Name "page")}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				{{- if eq (flagBaseType .Type) "bool"}}
				v, _ := cmd.Flags().GetBool("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "int"}}
				v, _ := cmd.Flags().GetInt("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "float64"}}
				v, _ := cmd.Flags().GetFloat64("{{.CLIFlag}}")
				{{- else if eq (flagBaseType .Type) "stringSlice"}}
				v, _ := cmd.Flags().GetStringSlice("{{.CLIFlag}}")
				{{- else}}
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				{{- end}}
				vars["{{.Name}}"] = v
			}
			{{- end}}
			{{- end}}

			// Validate flags
			fetchAll, _ := cmd.Flags().GetBool("all")
			if fetchAll && cmd.Flags().Changed("page") {
				return fmt.Errorf("--all and --page cannot be used together")
			}

			watchFlag, _ := cmd.Flags().GetBool("watch")
			intervalFlag, _ := cmd.Flags().GetInt("watch-interval")
			if intervalFlag <= 0 {
				intervalFlag = 5
			}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun && watchFlag {
				return fmt.Errorf("--watch and --dry-run cannot be used together")
			}
			if dryRun {
				return printDryRun(cmd, "query", "{{$res.ListQuery.GoName}}", vars)
			}

			q, err := getQuerier()
			if err != nil {
				return err
			}

			// fetchAndPrint executes the query and prints the result once.
			fetchAndPrint := func() error {
				if fetchAll {
					return {{$res.GoName | lower}}FetchAll(cmd, q, vars)
				}

				result, err := q.{{$res.ListQuery.GoName}}(context.Background(), vars)
				if err != nil {
					return err
				}
				{{- if $res.TableColumns}}
				// Extract data array from paginator response for table output
				if paginator, ok := result["{{$res.ListQuery.Name}}"].(map[string]any); ok {
					if data, ok := paginator["data"].([]any); ok {
						return printResult(cmd, data, {{$res.GoName | lower}}Columns)
					}
				}
				return printResult(cmd, result, nil)
				{{- else}}
				return printResult(cmd, result, nil)
				{{- end}}
			}

			if !watchFlag {
				return fetchAndPrint()
			}

			// Watch loop: clear screen, print header, fetch and print, sleep, repeat.
			for {
				fmt.Fprint(os.Stderr, "\033[2J\033[H")
				fmt.Fprintf(os.Stderr, "Every %ds — %s\n\n", intervalFlag, time.Now().Format("15:04:05"))

				if err := fetchAndPrint(); err != nil {
					fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				}

				time.Sleep(time.Duration(intervalFlag) * time.Second)
			}
		},
	}
	cmd.Flags().IntP("first", "n", 10, "Number of items to fetch per page")
	cmd.Flags().Int("page", 1, "Page number")
	cmd.Flags().Bool("all", false, "Fetch all pages")
	cmd.Flags().Bool("watch", false, "Poll and refresh output periodically")
	cmd.Flags().Int("watch-interval", 5, "Interval in seconds between refreshes (used with --watch)")
	{{range $res.ListQuery.Arguments -}}
	{{if and (ne .Name "first") (ne .Name "page") -}}
	{{if eq (flagBaseType .Type) "bool" -}}
	cmd.Flags().Bool("{{.CLIFlag}}", false, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "int" -}}
	cmd.Flags().Int("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "float64" -}}
	cmd.Flags().Float64("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "stringSlice" -}}
	cmd.Flags().StringSlice("{{.CLIFlag}}", nil, {{quote (enumHint .Description .Type)}})
	{{else -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote (enumHint .Description .Type)}})
	{{end -}}
	{{end -}}
	{{end -}}
	{{range $res.ListQuery.Arguments -}}
	{{if and (ne .Name "first") (ne .Name "page") .Type.IsRequired -}}
	_ = cmd.MarkFlagRequired("{{.CLIFlag}}")
	{{end -}}
	{{end}}
	{{range $res.ListQuery.Arguments -}}
	{{if and (ne .Name "first") (ne .Name "page") .Type.IsEnum -}}
	cmd.RegisterFlagCompletionFunc("{{.CLIFlag}}", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return {{enumValuesLiteral .Type.EnumValues}}, cobra.ShellCompDirectiveNoFileComp
	})
	{{end -}}
	{{end}}
	return cmd
}

func {{$res.GoName | lower}}FetchAll(cmd *cobra.Command, q *queries.Querier, vars map[string]any) error {
	const maxPages = 1000
	vars["first"] = 100 // Use large page size for --all
	var allData []any
	page := 1
	for {
		fmt.Fprintf(os.Stderr, "\rFetching page %d...", page)
		vars["page"] = page
		result, err := q.{{$res.ListQuery.GoName}}(context.Background(), vars)
		if err != nil {
			return fmt.Errorf("page %d: %w", page, err)
		}
		// Extract data array from paginator response
		if paginator, ok := result["{{$res.ListQuery.Name}}"].(map[string]any); ok {
			if data, ok := paginator["data"].([]any); ok {
				allData = append(allData, data...)
			}
			if info, ok := paginator["paginatorInfo"].(map[string]any); ok {
				if hasMore, ok := info["hasMorePages"].(bool); ok && !hasMore {
					break
				}
			} else {
				break
			}
		} else {
			// Not a paginator response, return single result
			return printResult(cmd, result, nil)
		}
		page++
		if page > maxPages {
			return fmt.Errorf("reached maximum page limit (%d); use --first and --page for manual pagination", maxPages)
		}
	}
	fmt.Fprintf(os.Stderr, "\r%-60s\n", fmt.Sprintf("Fetched %d items across %d pages.", len(allData), page))
	{{- if $res.TableColumns}}
	return printResult(cmd, allData, {{$res.GoName | lower}}Columns)
	{{- else}}
	return printResult(cmd, allData, nil)
	{{- end}}
}
{{end}}

{{range $mut := $res.Mutations}}
{{- if $mut.TableColumns}}
var {{$res.GoName | lower}}{{pascal $mut.CLIName}}Columns = []output.Column{
{{- range $mut.TableColumns}}
	{Header: {{quote .Header}}, Field: {{quote .Field}}},
{{- end}}
}
{{- end}}

func new{{$res.GoName}}{{pascal $mut.CLIName}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{$mut.CLIName}}",
		Short: {{quote $mut.Description}},
		{{- if $mut.InputExample}}
		Example: {{inputExampleBlock $res.Name $mut.CLIName $mut.InputFields $mut.InputExample | quote}},
		{{- else if $mut.InputFields}}
		Example: "  worksome {{$res.Name}} {{$mut.CLIName}} --input data.json{{with inputFlagExample $res.Name $mut.CLIName $mut.InputFields}}\n  {{.}}{{end}}",
		{{- end}}
		RunE: func(cmd *cobra.Command, args []string) error {
			// Validate output format
			if outputFlag, _ := cmd.Flags().GetString("output"); outputFlag != "" {
				if outputFlag != "json" && outputFlag != "table" {
					return fmt.Errorf("invalid output format %q: must be 'json' or 'table'", outputFlag)
				}
			}

			vars := make(map[string]any)

			// Load from input file if provided
			inputFile, _ := cmd.Flags().GetString("input")
			if inputFile != "" {
				fileVars, err := readInputFile(inputFile)
				if err != nil {
					return err
				}
				vars["input"] = fileVars
			}

			{{if $mut.InputFields -}}
			// Build input object from flags (flags override file values)
			inputObj, _ := vars["input"].(map[string]any)
			if inputObj == nil {
				inputObj = make(map[string]any)
			}
			{{range $mut.InputFields -}}
			if cmd.Flags().Changed("{{.CLIFlag}}") {
				{{- if eq (flagBaseType .Type) "int"}}
				v, _ := cmd.Flags().GetInt("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "float64"}}
				v, _ := cmd.Flags().GetFloat64("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "bool"}}
				v, _ := cmd.Flags().GetBool("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else if eq (flagBaseType .Type) "stringSlice"}}
				v, _ := cmd.Flags().GetStringSlice("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- else}}
				v, _ := cmd.Flags().GetString("{{.CLIFlag}}")
				inputObj["{{.Name}}"] = v
				{{- end}}
			}
			{{end -}}
			vars["input"] = inputObj

			if len(inputObj) == 0 && inputFile == "" {
				fmt.Fprintln(os.Stderr, "Warning: no input provided; use --input <file> or set individual flags")
			}
			{{end -}}

			dryRun, _ := cmd.Flags().GetBool("dry-run")
			if dryRun {
				return printDryRun(cmd, "mutation", "{{$mut.GoName}}", vars)
			}

			q, err := getQuerier()
			if err != nil {
				return err
			}

			result, err := q.{{$mut.GoName}}(context.Background(), vars)
			if err != nil {
				return err
			}
			{{- if $mut.TableColumns}}
			return printResult(cmd, result, {{$res.GoName | lower}}{{pascal $mut.CLIName}}Columns)
			{{- else}}
			return printResult(cmd, result, nil)
			{{- end}}
		},
	}
	cmd.Flags().String("input", "", "Path to JSON input file (use - for stdin)")
	{{range $mut.InputFields -}}
	{{if eq (flagBaseType .Type) "int" -}}
	cmd.Flags().Int("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "float64" -}}
	cmd.Flags().Float64("{{.CLIFlag}}", 0, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "bool" -}}
	cmd.Flags().Bool("{{.CLIFlag}}", false, {{quote (enumHint .Description .Type)}})
	{{else if eq (flagBaseType .Type) "stringSlice" -}}
	cmd.Flags().StringSlice("{{.CLIFlag}}", nil, {{quote (enumHint .Description .Type)}})
	{{else -}}
	cmd.Flags().String("{{.CLIFlag}}", "", {{quote (enumHint .Description .Type)}})
	{{end -}}
	{{end -}}
	{{range $mut.InputFields -}}
	{{if .Type.IsEnum -}}
	cmd.RegisterFlagCompletionFunc("{{.CLIFlag}}", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return {{enumValuesLiteral .Type.EnumValues}}, cobra.ShellCompDirectiveNoFileComp
	})
	{{end -}}
	{{end -}}
	return cmd
}
{{end}}
{{end}}{{/* not $res.Hoisted */}}
{{end}}

func printDryRun(cmd *cobra.Command, opType string, opName string, vars map[string]any) error {
	fmt.Fprintf(os.Stderr, "[dry-run] %s %s\n", opType, opName)
	data, _ := json.MarshalIndent(vars, "", "  ")
	fmt.Fprintf(os.Stdout, "%s\n", data)
	return nil
}
`

var rootTemplate = `// Code generated by worksome-cli codegen. DO NOT EDIT.
package commands

import "github.com/spf13/cobra"

// RegisterAll adds all generated resource commands to the root command.
func RegisterAll(root *cobra.Command) {
{{- range $res := .Resources}}
	root.AddCommand(New{{$res.GoName}}Cmd())
{{- end}}
}
`

func init() {
	// Register additional template functions for query building
	templateFuncs["buildQueryArgs"] = buildQueryArgs
	templateFuncs["buildQueryCallArgs"] = buildQueryCallArgs
	templateFuncs["buildMutationArgs"] = buildMutationArgs
	templateFuncs["buildMutationCallArgs"] = buildMutationCallArgs
	templateFuncs["buildSelectionHint"] = buildSelectionHint
	templateFuncs["hasIDArg"] = hasIDArg
	templateFuncs["not"] = func(b bool) bool { return !b }
	templateFuncs["inputFlagExample"] = inputFlagExample
	templateFuncs["inputFlagExampleHoisted"] = inputFlagExampleHoisted
	templateFuncs["flagBaseType"] = flagBaseType
	templateFuncs["enumHint"] = enumHint
	templateFuncs["shortDesc"] = shortDesc
	templateFuncs["enumValuesLiteral"] = enumValuesLiteral
	templateFuncs["inputExampleBlock"] = inputExampleBlock
	templateFuncs["inputExampleBlockHoisted"] = inputExampleBlockHoisted
}

// inputFlagExample returns an example command line showing up to 3 flag-based
// arguments for a mutation. Returns "" if there are no fields to show.
func inputFlagExample(resName, cliName string, fields []Argument) string {
	limit := 3
	if len(fields) < limit {
		limit = len(fields)
	}
	if limit == 0 {
		return ""
	}
	parts := []string{"worksome", resName, cliName}
	for _, f := range fields[:limit] {
		parts = append(parts, fmt.Sprintf(`--%s \"value\"`, f.CLIFlag))
	}
	return strings.Join(parts, " ")
}

// inputFlagExampleHoisted is like inputFlagExample but for hoisted commands
// where the resource name IS the command (no subcommand).
func inputFlagExampleHoisted(resName string, fields []Argument) string {
	limit := 3
	if len(fields) < limit {
		limit = len(fields)
	}
	if limit == 0 {
		return ""
	}
	parts := []string{"worksome", resName}
	for _, f := range fields[:limit] {
		parts = append(parts, fmt.Sprintf(`--%s \"value\"`, f.CLIFlag))
	}
	return strings.Join(parts, " ")
}

// inputExampleBlock returns a multi-line Example string for a mutation command
// that includes both usage and a JSON payload example when InputExample is set.
func inputExampleBlock(resName, cliName string, fields []Argument, inputExample string) string {
	var lines []string
	lines = append(lines, "  # Using a JSON input file:")
	lines = append(lines, fmt.Sprintf("  worksome %s %s --input payload.json", resName, cliName))
	if flagEx := inputFlagExample(resName, cliName, fields); flagEx != "" {
		lines = append(lines, "")
		lines = append(lines, "  # Using flags:")
		lines = append(lines, "  "+flagEx)
	}
	if inputExample != "" {
		lines = append(lines, "")
		lines = append(lines, "  # Example payload.json:")
		for _, l := range strings.Split(inputExample, "\n") {
			lines = append(lines, "  "+l)
		}
	}
	return strings.Join(lines, "\n")
}

// inputExampleBlockHoisted is like inputExampleBlock but for hoisted commands.
func inputExampleBlockHoisted(resName string, fields []Argument, inputExample string) string {
	var lines []string
	lines = append(lines, "  # Using a JSON input file:")
	lines = append(lines, fmt.Sprintf("  worksome %s --input payload.json", resName))
	if flagEx := inputFlagExampleHoisted(resName, fields); flagEx != "" {
		lines = append(lines, "")
		lines = append(lines, "  # Using flags:")
		lines = append(lines, "  "+flagEx)
	}
	if inputExample != "" {
		lines = append(lines, "")
		lines = append(lines, "  # Example payload.json:")
		for _, l := range strings.Split(inputExample, "\n") {
			lines = append(lines, "  "+l)
		}
	}
	return strings.Join(lines, "\n")
}

func buildQueryArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		gqlType := a.Type.Name
		if a.Type.IsList {
			gqlType = "[" + a.Type.ListItem.Name + "]"
			if a.Type.ListItem.IsRequired {
				gqlType = "[" + a.Type.ListItem.Name + "!]"
			}
		}
		if a.Type.IsRequired {
			gqlType += "!"
		}
		def := ""
		if a.DefaultValue != "" {
			def = " = " + a.DefaultValue
		}
		parts = append(parts, fmt.Sprintf("$%s: %s%s", a.Name, gqlType, def))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildQueryCallArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		parts = append(parts, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildMutationArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		gqlType := a.Type.Name
		if a.Type.IsList {
			inner := a.Type.ListItem.Name
			if a.Type.ListItem.IsRequired {
				inner += "!"
			}
			gqlType = "[" + inner + "]"
		}
		if a.Type.IsRequired {
			gqlType += "!"
		}
		parts = append(parts, fmt.Sprintf("$%s: %s", a.Name, gqlType))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildMutationCallArgs(args []Argument) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		parts = append(parts, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func buildSelectionHint(t TypeRef) string {
	if t.IsPaginator {
		return "{ id }"
	}
	if t.IsList {
		return "{ id }"
	}
	if t.IsScalar || t.IsEnum {
		return ""
	}
	return "{ id }"
}

func hasIDArg(args []Argument) bool {
	for _, a := range args {
		if a.Name == "id" {
			return true
		}
	}
	return false
}

// flagBaseType returns the Cobra flag type for an argument's TypeRef.
// Lists of scalars/enums map to "stringSlice"; other lists to "string" (JSON).
// Scalar pointers are unwrapped.
func flagBaseType(t TypeRef) string {
	if t.IsList {
		if t.ListItem != nil && (t.ListItem.IsScalar || t.ListItem.IsEnum) {
			return "stringSlice"
		}
		return "string"
	}
	goType := strings.TrimPrefix(t.GoType, "*")
	switch goType {
	case "bool":
		return "bool"
	case "int":
		return "int"
	case "float64":
		return "float64"
	default:
		return "string"
	}
}

// enumHint appends valid enum values to a flag description when the type is an enum.
func enumHint(desc string, t TypeRef) string {
	var values []string
	if t.IsEnum {
		values = t.EnumValues
	} else if t.IsList && t.ListItem != nil && t.ListItem.IsEnum {
		values = t.ListItem.EnumValues
	}
	if len(values) == 0 {
		return desc
	}
	display := values
	if len(display) > 5 {
		display = append(display[:5], "...")
	}
	return desc + " [" + strings.Join(display, ", ") + "]"
}

// shortDesc truncates a description to the first sentence for Short fields.
func shortDesc(s string) string {
	if i := strings.Index(s, ". "); i >= 0 {
		return s[:i+1]
	}
	if len(s) <= 100 {
		return s
	}
	if i := strings.LastIndex(s[:100], " "); i > 0 {
		return s[:i] + "..."
	}
	return s[:97] + "..."
}

// enumValuesLiteral returns a Go string slice literal for template use,
// e.g., `[]string{"ACTIVE", "DRAFT", "ARCHIVED"}`.
func enumValuesLiteral(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
